#----------port-------------------
server:
  port: 10179

spring:
  #----------database---------------
  datasource:
    jdbc-url: jdbc:mysql://xxx.xxx.xx.xx:xxxx/justlend-nile?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#----------logback---------------
logging:
  level:
    root: INFO
    org.tron.justlend.justlendapiserver: DEBUG

#----------properties---------------
uri:
  price-centre: https://c.tronlink.org/v1/cryptocurrency/getprice