#----------port-------------------
server:
  port: 10179

spring:
  #----------database---------------
  datasource:
    jdbc-url: jdbc:mysql://xxx.xxx.xx.xx:xxxx/justlend?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#----------logback---------------
logging:
  level:
    root: INFO
    org.tron.justlend.justlendapiserver: DEBUG

#----------properties---------------
uri:
  price-centre: https://c.tronlink.org/v1/cryptocurrency/getprice

task:
  enabled: true
  price-centre-feed:
    enabled: true
    interval: 60000
  strx-account-record-chaser:
    enabled: true
    interval: 4000
    range: 30000
    start: 61564523
  gov-account-record-chaser:
    enabled: true
    interval: 4000
    range: 500000
    start: 50343490